SET CONSTRAINTS ALL DEFERRED;
DO $$
DECLARE
  routine RECORD;
  drop_kind text;
BEGIN
  FOR routine IN
    SELECT p.oid, p.prokind, n.nspname, p.proname
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND NOT EXISTS (
        SELECT 1
        FROM pg_depend d
        WHERE d.objid = p.oid
          AND d.deptype = 'e'
      )
    ORDER BY p.oid DESC
  LOOP
    drop_kind := CASE routine.prokind
      WHEN 'p' THEN 'PROCEDURE'
      WHEN 'a' THEN 'AGGREGATE'
      ELSE 'FUNCTION'
    END;

    EXECUTE format(
      'DROP %s IF EXISTS %I.%I(%s) CASCADE',
      drop_kind,
      routine.nspname,
      routine.proname,
      pg_get_function_identity_arguments(routine.oid)
    );
  END LOOP;
END $$;

DROP TABLE IF EXISTS ASISTENCIA CASCADE;
DROP TABLE IF EXISTS BACKORDER CASCADE;
DROP TABLE IF EXISTS BANCO CASCADE;
DROP TABLE IF EXISTS BASEDISENO_PRUEBA CASCADE;
DROP TABLE IF EXISTS BASEDISENO_SETREGALO CASCADE;
DROP TABLE IF EXISTS BASE_DISENO CASCADE;
DROP TABLE IF EXISTS BASE_DISENO_CONSTRUCCION CASCADE;
DROP TABLE IF EXISTS BENEFICIO CASCADE;
DROP TABLE IF EXISTS CARACTERISTICA CASCADE;
DROP TABLE IF EXISTS CARACTERISTICA_BASEDISENO CASCADE;
DROP TABLE IF EXISTS CARGO CASCADE;
DROP TABLE IF EXISTS CATEGORIA CASCADE;
DROP TABLE IF EXISTS CATEGORIA_BASEDISENO CASCADE;
DROP TABLE IF EXISTS CATEGORIA_CATEGORIA CASCADE;
DROP TABLE IF EXISTS CHEQUE CASCADE;
DROP TABLE IF EXISTS CLASIFICACION CASCADE;
DROP TABLE IF EXISTS CLIENTE_B2C CASCADE;
DROP TABLE IF EXISTS COLECCION CASCADE;
DROP TABLE IF EXISTS COLOR CASCADE;
DROP TABLE IF EXISTS CONTRATO_BENEFICIO CASCADE;
DROP TABLE IF EXISTS CONTRATO_CARGO CASCADE;
DROP TABLE IF EXISTS CONTRATO_HORARIO CASCADE;
DROP TABLE IF EXISTS CONTRATO_PERSONAL CASCADE;
DROP TABLE IF EXISTS CORREO CASCADE;
DROP TABLE IF EXISTS COURIER CASCADE;
DROP TABLE IF EXISTS CRIPTOMONEDA CASCADE;
DROP TABLE IF EXISTS DEPARTAMENTO CASCADE;
DROP TABLE IF EXISTS DESCUENTO CASCADE;
DROP TABLE IF EXISTS DESCUENTO_ORDEN_B2B CASCADE;
DROP TABLE IF EXISTS DESCUENTO_ORDEN_B2C CASCADE;
DROP TABLE IF EXISTS DETALLE_MANIFIESTO_CARGO CASCADE;
DROP TABLE IF EXISTS DETALLE_ORDEN_B2B CASCADE;
DROP TABLE IF EXISTS DETALLE_ORDEN_B2C CASCADE;
DROP TABLE IF EXISTS DISTRIBUCION_PAGO_B2B CASCADE;
DROP TABLE IF EXISTS EMPLEADO CASCADE;
DROP TABLE IF EXISTS ENVIO_B2C CASCADE;
DROP TABLE IF EXISTS ERA CASCADE;
DROP TABLE IF EXISTS ESTATUS_BACKORDER CASCADE;
DROP TABLE IF EXISTS ESTATUS_FASE_PRODUCCION CASCADE;
DROP TABLE IF EXISTS ESTATUS_GANADOR CASCADE;
DROP TABLE IF EXISTS ESTATUS_INVENTARIO CASCADE;
DROP TABLE IF EXISTS ESTATUS_MEMBRESIA CASCADE;
DROP TABLE IF EXISTS ESTATUS_ORDEN_B2B CASCADE;
DROP TABLE IF EXISTS ESTATUS_ORDEN_COMPRA_B2C CASCADE;
DROP TABLE IF EXISTS ESTATUS_PAGO_MEMBRESIA CASCADE;
DROP TABLE IF EXISTS ESTATUS_PRECIO CASCADE;
DROP TABLE IF EXISTS ESTATUS_PUJA CASCADE;
DROP TABLE IF EXISTS ESTATUS_SUBASTA CASCADE;
DROP TABLE IF EXISTS FASE CASCADE;
DROP TABLE IF EXISTS FASE_DISENO CASCADE;
DROP TABLE IF EXISTS GANADOR CASCADE;
DROP TABLE IF EXISTS HISTORICO_BACKORDER CASCADE;
DROP TABLE IF EXISTS HISTORICO_EST_GANADOR CASCADE;
DROP TABLE IF EXISTS HISTORICO_EST_PUJA CASCADE;
DROP TABLE IF EXISTS HISTORICO_FASE_PRODUCCION CASCADE;
DROP TABLE IF EXISTS HISTORICO_INV_PRODUCTO CASCADE;
DROP TABLE IF EXISTS HISTORICO_MEMBRESIA CASCADE;
DROP TABLE IF EXISTS HISTORICO_ORDEN_COMPRA_B2B CASCADE;
DROP TABLE IF EXISTS HISTORICO_ORDEN_COMPRA_B2C CASCADE;
DROP TABLE IF EXISTS HISTORICO_PRECIO CASCADE;
DROP TABLE IF EXISTS HISTORICO_SUBASTA CASCADE;
DROP TABLE IF EXISTS HORARIO CASCADE;
DROP TABLE IF EXISTS INVENTARIO_MATERIAPRIMA CASCADE;
DROP TABLE IF EXISTS INVENTARIO_PRODUCTO CASCADE;
DROP TABLE IF EXISTS LINEA_CREDITO CASCADE;
DROP TABLE IF EXISTS LUGAR CASCADE;
DROP TABLE IF EXISTS MANIFIESTO_CARGO CASCADE;
DROP TABLE IF EXISTS MATERIAPRIMA CASCADE;
DROP TABLE IF EXISTS MEMBRESIA CASCADE;
DROP TABLE IF EXISTS MEMBRESIA_CLIENTE_B2C CASCADE;
DROP TABLE IF EXISTS META_MENSUAL CASCADE;
DROP TABLE IF EXISTS MOLDE CASCADE;
DROP TABLE IF EXISTS MONEDA CASCADE;
DROP TABLE IF EXISTS ORDEN_COMPRA_B2B CASCADE;
DROP TABLE IF EXISTS ORDEN_COMPRA_B2C CASCADE;
DROP TABLE IF EXISTS PAGO_B2B CASCADE;
DROP TABLE IF EXISTS PAGO_B2C CASCADE;
DROP TABLE IF EXISTS PAGO_MEMBRESIA CASCADE;
DROP TABLE IF EXISTS PAGO_SUBASTA CASCADE;
DROP TABLE IF EXISTS PAYPAL CASCADE;
DROP TABLE IF EXISTS PENALIZACION CASCADE;
DROP TABLE IF EXISTS PERSONA_JURIDICA CASCADE;
DROP TABLE IF EXISTS PIEZA CASCADE;
DROP TABLE IF EXISTS PRIVILEGIO CASCADE;
DROP TABLE IF EXISTS PRODUCTO CASCADE;
DROP TABLE IF EXISTS PROFESION CASCADE;
DROP TABLE IF EXISTS PROFESION_BASEDISENO CASCADE;
DROP TABLE IF EXISTS PRUEBA CASCADE;
DROP TABLE IF EXISTS PUJA CASCADE;
DROP TABLE IF EXISTS ROL CASCADE;
DROP TABLE IF EXISTS ROL_PRIVILEGIO CASCADE;
DROP TABLE IF EXISTS SEDE CASCADE;
DROP TABLE IF EXISTS SET_REGALO CASCADE;
DROP TABLE IF EXISTS SUBASTA CASCADE;
DROP TABLE IF EXISTS TABULADOR_SALARIAL CASCADE;
DROP TABLE IF EXISTS TARJETA_CREDITO CASCADE;
DROP TABLE IF EXISTS TARJETA_DEBITO CASCADE;
DROP TABLE IF EXISTS TASA_CAMBIO CASCADE;
DROP TABLE IF EXISTS TELEFONO CASCADE;
DROP TABLE IF EXISTS TIPO_CRIPTOMONEDA CASCADE;
DROP TABLE IF EXISTS TIPO_CUERPO CASCADE;
DROP TABLE IF EXISTS TIPO_TRANSPORTE CASCADE;
DROP TABLE IF EXISTS TRANSFERENCIA_BANCARIA CASCADE;
DROP TABLE IF EXISTS TRANSPORTE CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;
DROP TABLE IF EXISTS USUARIO_METODO_PAGO CASCADE;
drop table if exists fase_produccion cascade;

DO $$
DECLARE
  seq RECORD;
BEGIN
  FOR seq IN
    SELECT schemaname, sequencename
    FROM pg_sequences
    WHERE schemaname = 'public'
  LOOP
    EXECUTE format('DROP SEQUENCE IF EXISTS %I.%I CASCADE', seq.schemaname, seq.sequencename);
  END LOOP;
END $$;
