drop index if exists GENERA_FK;
drop index if exists ES_GANADOR2_FK;
drop index if exists ADJUDICACION_PK;
drop table if exists ADJUDICACION cascade;
drop index if exists ASISTE_FK;
drop index if exists ASISTENCIA_PK;
drop table if exists ASISTENCIA cascade;
drop index if exists SERA_PAGADA_FK;
drop index if exists BACKORDER_PK;
drop table if exists BACKORDER cascade;
drop index if exists BANCO_PK;
drop table if exists BANCO cascade;
drop index if exists PRUEBA_FK;
drop index if exists ES_PROBADA_FK;
drop index if exists BASEDISENO_PRUEBA_PK;
drop table if exists BASEDISENO_PRUEBA cascade;
drop index if exists AGRUPA_FK;
drop index if exists SE_AGRUPA_FK;
drop index if exists BASEDISENO_SETREGALO_PK;
drop table if exists BASEDISENO_SETREGALO cascade;
drop index if exists SE_DEFINE_FK;
drop index if exists TIENE_ASIGNADO_FK;
drop index if exists SE_MOLDEA_FK;
drop index if exists RELACIONA_FK;
drop index if exists PERTENECE2_FK;
drop index if exists ES_PARTE_DE2_FK;
drop index if exists BASE_DISENO_PK;
drop table if exists BASE_DISENO cascade;
drop index if exists SE_CONFORMA_FK;
drop index if exists CONSTRUYE_FK;
drop index if exists MOLDEARA_FK;
drop index if exists CONFORMA_FK;
drop index if exists BASE_DISENO_CONSTRUCCION_PK;
drop table if exists BASE_DISENO_CONSTRUCCION cascade;
drop index if exists BENEFICIO_PK;
drop table if exists BENEFICIO cascade;
drop index if exists CARACTERISTICA_PK;
drop table if exists CARACTERISTICA cascade;
drop index if exists CARACTERIZA_FK;
drop index if exists ES_CARACTERIZADA_FK;
drop index if exists CARACTERISTICA_BASEDISENO_PK;
drop table if exists CARACTERISTICA_BASEDISENO cascade;
drop index if exists ES_ASIGNADO_POR_FK;
drop index if exists TRABAJA_FK;
drop index if exists CARGO_PK;
drop table if exists CARGO cascade;
drop index if exists SE_DIVIDE_FK;
drop index if exists CATEGORIA_PK;
drop table if exists CATEGORIA cascade;
drop index if exists SE_RELACIONA_FK;
drop index if exists SE_VINCULA_FK;
drop index if exists CATEGORIA_BASEDISENO_PK;
drop table if exists CATEGORIA_BASEDISENO cascade;
drop index if exists VINCULA_FK;
drop index if exists CATEGORIA_CATEGORIA_PK;
drop table if exists CATEGORIA_CATEGORIA cascade;
drop index if exists ES_EXPEDIDO_FK;
drop index if exists CHEQUE_PK;
drop table if exists CHEQUE cascade;
drop index if exists CLASIFICACION_PK;
drop table if exists CLASIFICACION cascade;
drop index if exists CLASIFICA_FK;
drop index if exists ES_CLASIFICADA_FK;
drop index if exists CLASIFICACION_BASEDISENO_PK;
drop table if exists CLASIFICACION_BASEDISENO cascade;
drop index if exists DIRECCION_FISICA_FK;
drop index if exists CLIENTE_B2C_PK;
drop table if exists CLIENTE_B2C cascade;
drop index if exists ES_PARTE_DE_FK;
drop index if exists COLECCION_PK;
drop table if exists COLECCION cascade;
drop index if exists COLOR_PK;
drop table if exists COLOR cascade;
drop index if exists SE_EXPRESA_FK;
drop index if exists COLOR_OJO_PK;
drop table if exists COLOR_OJO cascade;
drop index if exists ES_GOZADO_FK;
drop index if exists GOZA_FK;
drop index if exists CONTRATO_BENEFICIO_PK;
drop table if exists CONTRATO_BENEFICIO cascade;
drop index if exists SE_ENCARGARA_FK;
drop index if exists ES_ENCARGADO_FK;
drop index if exists CONTRATO_CARGO_PK;
drop table if exists CONTRATO_CARGO cascade;
drop index if exists SE_ORGANIZA_FK;
drop index if exists CUMPLE_FK;
drop index if exists CONTRATO_HORARIO_PK;
drop table if exists CONTRATO_HORARIO cascade;
drop index if exists SE_ESTABLECE_FK;
drop index if exists LO_CONTRATAN2_FK;
drop index if exists CONTRATO_PERSONAL_PK;
drop table if exists CONTRATO_PERSONAL cascade;
drop index if exists POSEE_FK;
drop index if exists POSEE2_FK;
drop index if exists SE_USA_FK;
drop index if exists COORDINA_FK;
drop index if exists CORREO_PK;
drop table if exists CORREO cascade;
drop index if exists COURIER_PK;
drop table if exists COURIER cascade;
drop index if exists PERTENECE_A_LA_CADENA_FK;
drop index if exists CRIPTOMONEDA_PK;
drop table if exists CRIPTOMONEDA cascade;
drop index if exists DEPARTAMENTO_PK;
drop table if exists DEPARTAMENTO cascade;
drop index if exists DESCUENTO_PK;
drop table if exists DESCUENTO cascade;
drop index if exists DESCUENTA_FK;
drop index if exists SE_LE_DESCUENTA_FK;
drop index if exists DESCUENTO_ORDEN_B2B_PK;
drop table if exists DESCUENTO_ORDEN_B2B cascade;
drop index if exists SE_DESCUENTA_FK;
drop index if exists ES_DESCONTADO_FK;
drop index if exists DESCUENTO_ORDEN_B2C_PK;
drop table if exists DESCUENTO_ORDEN_B2C cascade;
drop index if exists SE_DESPACHA_FK;
drop index if exists SE_DESPACHA_EN_FK;
drop index if exists DETALLE_MANIFIESTO_CRAGO_PK;
drop table if exists DETALLE_MANIFIESTO_CRAGO cascade;
drop index if exists ESTA_DESCRITA_FK;
drop index if exists SE_PIDE_FK;
drop index if exists DETALLE_ORDEN_B2B_PK;
drop table if exists DETALLE_ORDEN_B2B cascade;
drop index if exists ES_DETALLADA_POR_FK;
drop index if exists SE_APARTA_FK;
drop index if exists DETALLE_ORDEN_B2C_PK;
drop table if exists DETALLE_ORDEN_B2C cascade;
drop index if exists SE_REPARTE_FK;
drop index if exists PAGAN_FK;
drop index if exists DISTRIBUCION_PAGO_B2B_PK;
drop table if exists DISTRIBUCION_PAGO_B2B cascade;
drop index if exists DIRECCION_FISICA2_FK;
drop index if exists LO_CONTRATAN_FK;
drop index if exists EMPLEADO_PK;
drop table if exists EMPLEADO cascade;
drop index if exists DIR_ORIGEN_B2C_FK;
drop index if exists DIR_ENVIO_B2C_FK;
drop index if exists VA_A_ENTREGAR_FK;
drop index if exists SERA_ENTREGADO2_FK;
drop index if exists ENVIO_B2C_PK;
drop table if exists ENVIO_B2C cascade;
drop index if exists PERTENECE_FK;
drop index if exists ERA_PK;
drop table if exists ERA cascade;
drop index if exists ESTATUS_BACKORDER_PK;
drop table if exists ESTATUS_BACKORDER cascade;
drop index if exists ESTATUS_FASE_PRODUCCION_PK;
drop table if exists ESTATUS_FASE_PRODUCCION cascade;
drop index if exists ESTATUS_INVENTARIO_PK;
drop table if exists ESTATUS_INVENTARIO cascade;
drop index if exists ESTATUS_MEMBRESIA_PK;
drop table if exists ESTATUS_MEMBRESIA cascade;
drop index if exists ESTATUS_ORDEN_B2B_PK;
drop table if exists ESTATUS_ORDEN_B2B cascade;
drop index if exists ESTATUS_ORDEN_COMPRA_B2C_PK;
drop table if exists ESTATUS_ORDEN_COMPRA_B2C cascade;
drop index if exists ESTATUS_ORDEN_SUBASTA_PK;
drop table if exists ESTATUS_ORDEN_SUBASTA cascade;
drop index if exists ESTATUS_PAGO_MEMBRESIA_PK;
drop table if exists ESTATUS_PAGO_MEMBRESIA cascade;
drop index if exists ESTATUS_PRECIO_PK;
drop table if exists ESTATUS_PRECIO cascade;
drop index if exists ESTATUS_PUJA_PK;
drop table if exists ESTATUS_PUJA cascade;
drop index if exists ESTATUS_SUBASTA_PK;
drop table if exists ESTATUS_SUBASTA cascade;
drop index if exists MANEJAN_FK;
drop index if exists SE_MANEJA_FK;
drop index if exists FASE_CARGO_PK;
drop table if exists FASE_CARGO cascade;
drop index if exists SE_PRUEBA_FK;
drop index if exists TIENE_FK;
drop index if exists FASE_DISENO_PK;
drop table if exists FASE_DISENO cascade;
drop index if exists TRABAJA_EN_FK;
drop index if exists SUJETO_A_FK;
drop index if exists FASE_EMPLEADO_PK;
drop table if exists FASE_EMPLEADO cascade;
drop index if exists LO_SIGUE_FK;
drop index if exists SIGUE_FK;
drop index if exists FASE_PRODUCCION_PK;
drop table if exists FASE_PRODUCCION cascade;
drop index if exists SE_LE_REGISTRA_FK;
drop index if exists ES_REGISTRADO_FK;
drop index if exists HISTORICO_BACKORDER_PK;
drop table if exists HISTORICO_BACKORDER cascade;
drop index if exists SE_DESCRIBE_FK;
drop index if exists ES_DESCRITA_FK;
drop index if exists HISTORICO_EST_ORD_SUBASTA_PK;
drop table if exists HISTORICO_EST_ORD_SUBASTA cascade;
drop index if exists RESENA_FK;
drop index if exists SE_REGISTRA_FK;
drop index if exists HISTORICO_FASE_PRODUCCION_PK;
drop table if exists HISTORICO_FASE_PRODUCCION cascade;
drop index if exists EXPLICA_FK;
drop index if exists SE_CERTIFICA_FK;
drop index if exists HISTORICO_INV_PRODUCTO_PK;
drop table if exists HISTORICO_INV_PRODUCTO cascade;
drop index if exists ES_REGISTRADA_FK;
drop index if exists DESCRIBE_FK;
drop index if exists HISTORICO_MEMBRESIA_PK;
drop table if exists HISTORICO_MEMBRESIA cascade;
drop index if exists VA_REGISTRADA_FK;
drop index if exists HISTORICO_ORDEN_COMPRA_B2B_PK;
drop table if exists HISTORICO_ORDEN_COMPRA_B2B cascade;
drop index if exists CONDICIONADO_FK;
drop index if exists SUJETA_A_FK;
drop index if exists HISTORICO_ORDEN_COMPRA_B2C_PK;
drop table if exists HISTORICO_ORDEN_COMPRA_B2C cascade;
drop index if exists ESTA_PAUTADO_FK;
drop index if exists SE_VALUA_FK;
drop index if exists HISTORICO_PRECIO_PK;
drop table if exists HISTORICO_PRECIO cascade;
drop index if exists ES_DETERMINADA_FK;
drop index if exists TIENE_UN_ESTATUS_FK;
drop index if exists HISTORICO_SUBASTA_PK;
drop table if exists HISTORICO_SUBASTA cascade;
drop index if exists HORARIO_PK;
drop table if exists HORARIO cascade;
drop index if exists ES_ALMACENADA_FK;
drop index if exists ALMACENA_FK;
drop index if exists INVENTARIO_MATERIAPRIMA_PK;
drop table if exists INVENTARIO_MATERIAPRIMA cascade;
drop index if exists SE_SUBASTA_FK;
drop index if exists SE_ALMACENA_FK;
drop index if exists CONTIENE_FK;
drop index if exists INVENTARIO_PRODUCTO_PK;
drop table if exists INVENTARIO_PRODUCTO cascade;
drop index if exists ES_ASIGNADO2_FK;
drop index if exists LINEA_CREDITO_PK;
drop table if exists LINEA_CREDITO cascade;
drop index if exists DIVIDE_FK;
drop index if exists LUGAR_PK;
drop table if exists LUGAR cascade;
drop index if exists SU_ORIGEN_ES_FK;
drop index if exists SE_ENTREGA_EN_FK;
drop index if exists ES_TRANSPORTADA_FK;
drop index if exists MANIFIESTO_CARGO_PK;
drop table if exists MANIFIESTO_CARGO cascade;
drop index if exists MATERIAPRIMA_PK;
drop table if exists MATERIAPRIMA cascade;
drop index if exists MEMBRESIA_PK;
drop table if exists MEMBRESIA cascade;
drop index if exists COMPRA_FK;
drop index if exists ES_ADQUIRIDA_FK;
drop index if exists MEMBRESIA_CLIENTE_B2C_PK;
drop table if exists MEMBRESIA_CLIENTE_B2C cascade;
drop index if exists META_MENSUAL_PK;
drop table if exists META_MENSUAL cascade;
drop index if exists MOLDE_PK;
drop table if exists MOLDE cascade;
drop index if exists SE_REALIZA_EL_PAGO_FK;
drop index if exists ES_PAGADO_MEDIANTE_FK;
drop index if exists SE_PAGA_MEDIANTE_FK;
drop index if exists ES_REALIZADO_EL_PAGO_FK;
drop index if exists MONEDA_PK;
drop table if exists MONEDA cascade;
drop index if exists VENDE_FK;
drop index if exists COMPRA_MASIVAMENTE_FK;
drop index if exists ORDEN_COMPRA_B2B_PK;
drop table if exists ORDEN_COMPRA_B2B cascade;
drop index if exists ES_VENDEDOR_FK;
drop index if exists QUIERE_COMPRAR_FK;
drop index if exists SERA_ENTREGADO_FK;
drop index if exists ORDEN_COMPRA_B2C_PK;
drop table if exists ORDEN_COMPRA_B2C cascade;
drop index if exists GENERA2_FK;
drop index if exists ES_PENALIZADO_FK;
drop index if exists ORDEN_SUBASTA_PK;
drop table if exists ORDEN_SUBASTA cascade;
drop index if exists SE_REALIZA_EL_PAGO2_FK;
drop index if exists ES_ABONADO_FK;
drop index if exists ES_SALDADO_FK;
drop index if exists PAGO_B2B_PK;
drop table if exists PAGO_B2B cascade;
drop index if exists ES_PAGADO_MEDIANTE2_FK;
drop index if exists SE_PAGARA_FK;
drop index if exists SE_UTILIZA_FK;
drop index if exists SE_UTILIZARA_FK;
drop index if exists SE_VA_PAGAR_FK;
drop index if exists ES_CONCILIADO_FK;
drop index if exists PAGO_B2C_PK;
drop table if exists PAGO_B2C cascade;
drop index if exists SE_PAGA_MEDIANTE2_FK;
drop index if exists ES_CLASIFICADA_POR_FK;
drop index if exists SE_PAGA_FK;
drop index if exists ES_REALIZADA_FK;
drop index if exists PAGO_MEMBRESIA_PK;
drop table if exists PAGO_MEMBRESIA cascade;
drop index if exists ES_REALIZADO_EL_PAGO2_FK;
drop index if exists ES_VALIDA_FK;
drop index if exists ES_PAGADO_FK;
drop index if exists PAGO_SUBASTA_PK;
drop table if exists PAGO_SUBASTA cascade;
drop index if exists SE_USA2_FK;
drop index if exists PAYPAL_PK;
drop table if exists PAYPAL cascade;
drop index if exists ES_PENALIZADO2_FK;
drop index if exists PENALIZACION_PK;
drop table if exists PENALIZACION cascade;
drop index if exists DIR_FISICA_JURIDICA_FK;
drop index if exists ES_ASIGNADO_FK;
drop index if exists DIR_FISCAL_JURIDICA_FK;
drop index if exists PERSONA_JURIDICA_PK;
drop table if exists PERSONA_JURIDICA cascade;
drop index if exists PIEZA_PK;
drop table if exists PIEZA cascade;
drop index if exists PRIVILEGIO_PK;
drop table if exists PRIVILEGIO cascade;
drop index if exists SE_DISENA_FK;
drop index if exists SE_CARACTERIZA_FK;
drop index if exists EJERCE_FK;
drop index if exists SE_CLASIFICA_FK;
drop index if exists SE_AGRUPARA_FK;
drop index if exists SE_CATEGORIZA_FK;
drop index if exists SE_CREARA_FK;
drop index if exists PRODUCTO_PK;
drop table if exists PRODUCTO cascade;
drop index if exists PROFESION_PK;
drop table if exists PROFESION cascade;
drop index if exists EJERCIDA_FK;
drop index if exists SE_EJERCE_FK;
drop index if exists PROFESION_BASEDISENO_PK;
drop table if exists PROFESION_BASEDISENO cascade;
drop index if exists PRUEBA_PK;
drop table if exists PRUEBA cascade;
drop index if exists NECESITA_FK;
drop index if exists SE_REALIZA_FK;
drop index if exists OFERTA_FK;
drop index if exists ES_GANADOR_FK;
drop index if exists OFERTAN_FK;
drop index if exists PUJA_PK;
drop table if exists PUJA cascade;
drop index if exists ROL_PK;
drop table if exists ROL cascade;
drop index if exists USA_FK;
drop index if exists HACE_USO_FK;
drop index if exists ROL_PRIVILEGIO_PK;
drop table if exists ROL_PRIVILEGIO cascade;
drop index if exists ESTA_UBICADA_FK;
drop index if exists SEDE_PK;
drop table if exists SEDE cascade;
drop index if exists SET_REGALO_PK;
drop table if exists SET_REGALO cascade;
drop index if exists SE_SUBASTA2_FK;
drop index if exists SUBASTA_PK;
drop table if exists SUBASTA cascade;
drop index if exists TABULADOR_SALARIAL_PK;
drop table if exists TABULADOR_SALARIAL cascade;
drop index if exists EMITE_FK;
drop index if exists TARJETA_CREDITO_PK;
drop table if exists TARJETA_CREDITO cascade;
drop index if exists ES_EMITIDO_FK;
drop index if exists TARJETA_DEBITO_PK;
drop table if exists TARJETA_DEBITO cascade;
drop index if exists SE_JUSTIFICA_FK;
drop index if exists TASA_CAMBIO_PK;
drop table if exists TASA_CAMBIO cascade;
drop index if exists ADMINISTRA_FK;
drop index if exists ADMINISTRA2_FK;
drop index if exists CUENTA_CON_FK;
drop index if exists TELEFONO_PK;
drop table if exists TELEFONO cascade;
drop index if exists TIPO_CRIPTOMONEDA_PK;
drop table if exists TIPO_CRIPTOMONEDA cascade;
drop index if exists TIPO_CUERPO_PK;
drop table if exists TIPO_CUERPO cascade;
drop index if exists TIPO_TRANSPORTE_PK;
drop table if exists TIPO_TRANSPORTE cascade;
drop index if exists SE_TINTA_FK;
drop index if exists TONO_PIEL_PK;
drop table if exists TONO_PIEL cascade;
drop index if exists ES_TRANSFERIDO_FK;
drop index if exists TRANSFERENCIA_BANCARIA_PK;
drop table if exists TRANSFERENCIA_BANCARIA cascade;
drop index if exists SE_IDENTIFICA_POR_FK;
drop index if exists TRANSPORTE_PK;
drop table if exists TRANSPORTE cascade;
drop index if exists CREA_FK;
drop index if exists CREA2_FK;
drop index if exists SE_CREA_FK;
drop index if exists SE_LE_ASIGNA_FK;
drop index if exists USUARIO_PK;
drop table if exists USUARIO cascade;
drop index if exists ES_VALIDADA_FK;
drop index if exists PERTENECE_A_FK;
drop index if exists REGISTRA_FK;
drop index if exists USUARIO_METODO_PAGO_PK;
drop table if exists USUARIO_METODO_PAGO cascade;